### ISSUE TITLE
newbie question

### ISSUE THREAD

**Issue by omarcostahamido** [sauraen/HQStreamer2#4]
the readme says:
"Host a session locally: Allow clients to connect directly to your computer and receive audio without an intermediate server. Requires port forwarding setup and lots of upload bandwidth."

why is it not possible to use this mode of no intermediate server to work across the internet?

**Comment by sauraen** [comment]
It is possible to use this mode over the internet. You just have to be able to configure your network so that incoming requests to your external IP are routed to your computer and to HQStreamer2. This would typically consist of two steps:
* setting up port forwarding on your router to route port 21568 on WAN to your computer's IP address on LAN
* telling your operating system's firewall to accept incoming connections on port 21568

In addition, using this effectively requires your router to have a static public IP address, and your computer to not be connected through a VPN. Many ISPs nowadays do not use static IPs (in fact some use second-level NAT), and many users prefer to use a VPN for privacy reasons.

Since this is technical, most users wouldn't be able to do this. But, the option is provided for LAN use, or for users who do know how to do this.
